services:
  localstack:
    image: localstack/localstack-pro:stable
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    env_file:
      - .env
    environment:
      - SERVICES=iam,ec2,s3,dynamodb,lambda,rds
      - PERSISTENCE=true
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
